#!/bin/bash

# Replace these three settings.
TMPDIR="/tmp"
PROJDIR="/var/www/anime-kita.dk/selvbetjening/django/kita-site"
PIDFILE="$TMPDIR/selvkita.pid"
SOCKET="$TMPDIR/selvkita.socket"

cd $TMPDIR
if [ -f $PIDFILE ]; then
    kill `cat -- $PIDFILE`
    rm -f -- $PIDFILE
fi

cd $PROJDIR
exec /usr/bin/env - \
  PYTHONPATH="../python:.." \
  ./manage.py runfcgi socket=$SOCKET pidfile=$PIDFILE maxchildren=3 workdir=/var/www/anime-kita.dk/selvbetjening/django/ maxrequests=400 maxspare=1
